### ISSUE TITLE
libuuid cannot be found when pkg-config is not installed

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/libignition-cmake0-feedstock#32] opened 2022-10-21 00:59 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When trying to compile ros-ign-gazebo, I get the following error:

```
CMake Error at /home/tobias/mambaforge/conda-bld/ros-humble-ros-ign-gazebo_1666312048419/_build_env/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find UUID (missing: UUID_FOUND)
Call Stack (most recent call first):
  /home/tobias/mambaforge/conda-bld/ros-humble-ros-ign-gazebo_1666312048419/_build_env/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/tobias/mambaforge/conda-bld/ros-humble-ros-ign-gazebo_1666312048419/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share/cmake/ignition-cmake2/cmake2/FindUUID.cmake:67 (find_package_handle_standard_args)
  /home/tobias/mambaforge/conda-bld/ros-humble-ros-ign-gazebo_1666312048419/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/cmake/ignition-transport11/ignition-transport11-config.cmake:95 (find_package)
  /home/tobias/mambaforge/conda-bld/ros-humble-ros-ign-gazebo_1666312048419/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/cmake/ignition-gazebo6/ignition-gazebo6-config.cmake:94 (find_package)
  CMakeLists.txt:44 (find_package)
```

### Installed packages

```shell
+ libignition-cmake2                                       2.15.0  h27087fc_0           conda-forge/linux-64                           Cached
  + libignition-common4                                       4.5.1  h8419eb0_1           conda-forge/linux-64                           Cached
  + libignition-fuel-tools7                                   7.1.0  h08d22d4_1           conda-forge/linux-64                           Cached
  + libignition-gazebo6                                      6.12.0  h8739608_1           conda-forge/linux-64                           Cached
  + libignition-gui6                                          6.6.1  hcb1a778_1           conda-forge/linux-64                           Cached
  + libignition-math6                                        6.13.0  py310h3f2b827_0      conda-forge/linux-64                           Cached
  + libignition-msgs8                                         8.6.0  h07fcb4f_1           conda-forge/linux-64                           Cached
  + libignition-physics5                                      5.2.0  h27087fc_0           conda-forge/linux-64                           Cached
  + libignition-plugin1                                       1.3.0  h27087fc_0           conda-forge/linux-64                           Cached
  + libignition-rendering6                                    6.5.1  hbfd296a_0           conda-forge/linux-64                           Cached
  + libignition-sensors6                                      6.6.0  h425f889_2           conda-forge/linux-64                           Cached
  + libignition-tools1                                        1.5.0  h06cd983_1           conda-forge/linux-64                           Cached
  + libignition-transport11                                  11.2.0  h034a4ee_1           conda-forge/linux-64                           Cached
  + libignition-utils1                                        1.4.0  h27087fc_0           conda-forge/linux-64                           Cached
  + libuuid                                                  2.32.1  h7f98852_1000        conda-forge/linux-64                           Cached
```

### Environment info

```shell
n/a
```

**Comment by traversaro** [comment] 2022-10-21 09:43
There is something strange, I triggered https://github.com/conda-forge/libignition-launch-feedstock/pull/18 to test a project that does `find_package(ignition-gazebo6)`, and everything is building fine. Was this an error in a local build or CI?

**Comment by traversaro** [comment] 2022-10-21 10:09
I found the actual failing job: https://github.com/RoboStack/ros-humble/actions/runs/3287250154/jobs/5416215581 .

**Comment by traversaro** [comment] 2022-10-21 10:13
I may be wrong, but it seems to me that `pkg-config` is not installed in the job, while in https://github.com/conda-forge/libignition-launch-feedstock/pull/18 it is installed. In theory `uuid` should be found even without pkg-config, but a quick fix may be to just install pkg-config ?

**Comment by traversaro** [comment] 2022-10-21 10:16
Just to be sure of this, we could also add `pkg-config` as a run dependency of libignition-common .

**Comment by traversaro** [comment] 2022-10-21 10:33
> Just to be sure of this, we could also add `pkg-config` as a run dependency of libignition-common .

This is not a good idea probably, as `pkg-config` should be installed in the `build` environment, not in the host one.

**Comment by traversaro** [comment] 2022-10-21 11:18
I was not able to reproduce the problem on Azure as the system pkg-config if I did not listed explicitly the pkg-config dependency in the conda recipe. Anyhow, I was able to reproduce it in docker, and I found that I was the one that introduced it in the first place in https://github.com/gazebosim/gz-cmake/pull/95 . : )

Anyhow, it should be fixed by https://github.com/conda-forge/libignition-cmake0-feedstock/pull/33 .

**Closed** 2022-10-21 11:25 UTC
Labels: bug

**Comment by Tobias-Fischer** [comment] 2022-10-21 17:56
Thanks a lot!!
